# Generated by Django 2.1.7 on 2019-11-09 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('52357198-3f55-4c85-bff6-715bc0ed7c1b'), primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievement/image')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_achievements',
            },
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('51451b9e-32d1-4ad9-a857-be539a9811ae'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity/image')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_activities',
            },
        ),
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('67077356-49ed-4b01-9c0c-f3436c5a8967'), primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_contacts',
            },
        ),
        migrations.CreateModel(
            name='SchoolExtracurricular',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('83a30d6f-591d-474b-a7a6-5fb7e1841722'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ekskul/image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_extracurriculars',
            },
        ),
        migrations.CreateModel(
            name='SchoolMajor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('53e531b4-86f6-4713-bd5f-2865162a6331'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='major/image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_majors',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2f21fb80-48fb-4ed4-bade-d5c235e30688'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher/photo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'techers',
            },
        ),
        migrations.CreateModel(
            name='TeacherContact',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8ca44012-e8da-40ee-894e-3c6a0b3a79d3'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Teacher')),
            ],
            options={
                'db_table': 'techer_contacts',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school/image'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2075e210-2e50-4000-8d7e-6e82907fb026'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
        migrations.AddField(
            model_name='schoolmajor',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
        migrations.AddField(
            model_name='schoolextracurricular',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
        migrations.AddField(
            model_name='schoolcontact',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
        migrations.AddField(
            model_name='schoolachievement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School'),
        ),
    ]
