# Generated by Django 2.1.7 on 2019-11-09 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20191110_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3decf44-614b-4b89-a814-fd97c67975d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolachievement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc9005a4-ba3a-449e-bfe8-19a302be61c4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolactivity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19a590b7-4b04-4341-b7fb-45ab23a73362'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('198a24c0-a071-4b0e-83fe-dcc04161ae11'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolextracurricular',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d9c0105-0882-4d2b-ae13-26b6f37d26d3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec9fc648-2578-4eb0-bd3a-47c9dc089836'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54caeb44-b7c6-497e-8748-5d422b9568ee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teachercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8f2d67a-d6b1-4d64-aac2-b04de909dcaf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
