# Generated by Django 2.1.7 on 2019-11-09 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20191110_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e877d06f-682d-4996-85d1-26a40c3f18e0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolachievement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e84243a5-f51e-406d-8c82-26e9e8a9e0e5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolactivity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a246d6e7-d8ce-4bdf-9140-b02c86fbb577'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fc27eb9-dd3d-4af0-afb5-898c92fec344'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolextracurricular',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9132f435-a207-46d2-aaf0-26d1cd61ab58'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50b3e74e-10a1-49f2-8762-f9732f5f90d8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8695004-eaab-4279-b781-bf5d50f09660'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teachercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3093c769-3677-4957-8951-523b7876d155'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
