# Generated by Django 2.1.7 on 2019-11-09 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20191110_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c3ca28c-1887-4491-ad1b-43f5ca826524'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolachievement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e3fac3f-a24c-465a-a1fe-035f32636a78'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolactivity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bf29b0e-3e9a-43ff-a72e-974f6bd277b1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33a56622-573e-42cc-b8a2-0362e7c8c1c3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolextracurricular',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04e3ed5a-5968-4bda-8e4b-1552a97c04ec'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf730e31-b729-4f9a-9669-413bced5d162'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb027e69-267b-4503-94ac-7e45d5f2568a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teachercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f36ee0e1-1a6d-476d-9ff9-3169d7eb2e97'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
