# Generated by Django 2.1.7 on 2019-11-11 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20191110_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
