# Generated by Django 2.1.7 on 2019-11-15 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20191111_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_school', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True)),
                ('periode', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_year', models.CharField(blank=True, max_length=4, null=True)),
                ('registration_moth', models.CharField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=32, null=True)),
                ('student_name', models.CharField(blank=True, max_length=128, null=True)),
                ('nisn', models.CharField(blank=True, max_length=128, null=True)),
                ('national_exam_number', models.CharField(blank=True, max_length=128, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True)),
                ('skhun_number', models.CharField(blank=True, max_length=128, null=True)),
                ('average_national_exam_scores', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('parent_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=128, null=True)),
                ('number_of_siblings', models.PositiveIntegerField(default=0)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')], default=0)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=128, null=True)),
                ('faith', models.PositiveSmallIntegerField(choices=[(0, 'Islam'), (1, 'Kristen'), (2, 'Katholik'), (3, 'Budha'), (4, 'Hindu'), (5, 'Lain-lain')], default=0)),
                ('student_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_student', models.ImageField(blank=True, null=True, upload_to='registration/student')),
                ('image_skhun', models.ImageField(blank=True, null=True, upload_to='registration/skhun')),
                ('to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School')),
            ],
            options={
                'db_table': 'student_registrations',
            },
        ),
    ]
