# Generated by Django 2.1.7 on 2019-11-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_studentregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='registration_moth',
            new_name='registration_month',
        ),
    ]
