# Generated by Django 2.1.7 on 2019-11-15 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20191116_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School')),
            ],
            options={
                'db_table': 'school_tokens',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_registration_tokens',
            },
        ),
    ]
