# Generated by Django 2.1.7 on 2019-11-16 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_abstractschool_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMagazine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.School')),
            ],
            options={
                'db_table': 'school_magazines',
            },
        ),
        migrations.CreateModel(
            name='SchoolMagazineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.SchoolActivity')),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.SchoolMagazine')),
            ],
            options={
                'db_table': 'school_magazine_activities',
            },
        ),
    ]
