# Generated by Django 2.1.7 on 2019-11-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20191116_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Province'),
        ),
    ]
