# Generated by Django 2.1.7 on 2019-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_auto_20191116_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Negeri'), (1, 'Swasta')], max_length=8, null=True),
        ),
    ]
