# Generated by Django 2.2.9 on 2019-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20191116_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lat',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='lng',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
