# Generated by Django 2.2.9 on 2019-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_auto_20191224_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
